# Generated by Django 5.2.8 on 2026-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0003_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                default="Medium",
                max_length=20,
            ),
        ),
    ]
